# -------------------------------------------------------------------------
# Dockerfile para Nginx com Módulo 'mirror' (ngx_http_mirror_module)
# -------------------------------------------------------------------------

FROM nginx:stable-bullseye

RUN apt-get update && apt-get install -y nginx-extras && rm -rf /var/lib/apt/lists/*

COPY ./config/nginx.conf /etc/nginx/nginx.conf

# RUN nginx -t